os:
  - linux
  - osx

language: c

sudo: false

addons:
  apt:
    packages:
      - valgrind
env:
  - RL_DEBUG=0
  - RL_DEBUG=1

compiler:
  - clang
  - gcc

script:
  - make
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install --HEAD valgrind; fi
  - make vtest

notifications:
  email: false
